### ISSUE TITLE
Option to turn off Most Played / Last 7 Days / Last 30 Days game

### ISSUE THREAD

**Issue by Vackz** [felixkmh/StartPage-for-Playnite#60]

**Comment by felixkmh** [comment]
Did you mean turn off?

**Comment by Vackz** [comment]
yes, sorry i forgot to type in "off"

**Comment by ATNewHope** [comment]
It's really nice to enjoy such a start page.
However, if I want it being the "starting page", when I open my laptop and playnite at class (I also use playnite as software launcher) and 3 game icons pop up, my professor may see it. That's a bit annoying for me.
Though it might be a hard work (I'm not sure), I really wish the option could be added. Thank you very much in advance.

**Comment by ResoundingSounds** [comment]
Just want to say, great add-on, it's probably the best way to quickly look at recent games and achievements.
I would also like to turn off those boxes. I use "Most Played" as a SteamVR button, so it would be sort of nice to be able to toggle that one separately, or to have a dedicated SteamVR button.
(SteamVR has a bug where it accumulates hours even when it's off, guaranteeing that it's listed as most played since it ends up accumulating thousands of hours)

**Comment by felixkmh** [comment]
done in v1.10.0

**Comment by chocolatechipcats** [comment]
Addendum: Would it be much effort to make each one separately toggleable? 

Currently, it's on/off for the entire thing, when I would just like to hide the 'most played' (because nothing's going to match the number of hours I've spent on Windows Solitaire, lol).

Thanks for consideration :)
